version: '3'

services:
  postgres:
    image: 'postgres:14.5'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  # pgadmin container service work depends on postgres container service (db_postgres)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=adminx@adminx.com
      - PGADMIN_DEFAULT_PASSWORD=adminx
    ports:
      - 5050:80
    restart: always
    volumes:
      - ./db-data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  movie-api:
    build:
      context: ./../backend
      dockerfile: movie-service.dockerfile
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
